### ISSUE TITLE
Row components for data explorer

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-dapp#320]
- [x]  Create three styles of row: public, vault, and private
- [x] Vault: Font color: #575757, bold (except not in button or Vault tag); Icon color: #575757
- [x] Private (from unlocked vault): Font #575757, regular (not bold); Icon color: #A4A8AE
- [x] Public: Font color: #7B8087, regular; Icon color: #A4A8AE
- [x] Public row: Display Name column from key (i.e. gitcoin.avatar becomes Gitcoin Avatar)
- [x] Public row: Display Content column from value
- [x] Public row: Text: Display text. And ensure can support emojis.
- [ ] Public row: List (array): Display text separated by commas.
- [ ] Public row: Claim: Display text
- [x] Public row: Image: Display image file as a fill inside a rounded rectangle
- [x] Public row: Display Space column from space name, use "3Box" for name of generic space
- [x] Public row: Display Type column from value type (text, list, claim, image)
- [x] Public row: Display Privacy column as public icon
- [ ] Public row: Display Last Updated from timestamp. Make human readable:
- [ ] Public row: XX mins ago to 60 mins
- [ ] Public row: XX hours ago to 24 hrs
- [ ] Public row: XX days ago to 5 days
- [ ] Public row: then go to date in form of "February 12, 2019"
- [x] Vault row: Display a Vault row for every space with encrypted data possessed by the user
- [x] Vault row: Make text darker grey (#575757) and bold
- [x] Vault row: Display Name as "Private <Space> Data" with a folder icon before it
- [x] Vault row: Display Content as "Unlock to Open" button
- [x] Vault row: Display Space as "<Space> Vault"
- [x] Vault row: Display Type as "Vault"
- [x] Vault row: Display Privacy as lock icon
- [x] Vault row: When user clicks button, change button text from "Unlock to open" to "Approve in your wallet" and add a loading spinner inside the button. Also add a "Retry" option to the right of the button. If user closes the web3 modal before approving or if they click retry, then return button to original state.
- [ ] Vault row: After user approves in wallet, display contents of the vault as private rows on the top of the list of data below it.
- [x] Private row: Display Name, same as rules for Public Row
- [x] Private row: Display Content, same as rules for Public Row
- [x] Private row: Display Space as "<Space> Vault"
- [x] Private row: Display Type as: text, list, claim, image
- [x] Private row: Display Privacy as lock icon
- [x] Private row: Display Last Updated, same as rules for Public Row
